[package]
name = "uu_cksum"
version = "0.0.17"
authors = ["uutils developers"]
license = "MIT"
description = "cksum ~ (uutils) display CRC and size of input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/cksum"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2021"

[lib]
path = "src/cksum.rs"

[dependencies]
clap = { workspace=true }
uucore = { version=">=0.0.17", package="uucore", path="../../uucore", features=["sum"] }
hex = { workspace=true }
md-5 = { workspace=true }
sha1 = { workspace=true }
sha2 = { workspace=true }
blake2b_simd = { workspace=true }
blake3 = { workspace=true }
sm3 = { workspace=true }

[[bin]]
name = "cksum"
path = "src/main.rs"
