[package]
name = "uu_tr"
version = "0.0.7"
authors = ["uutils developers"]
license = "MIT"
description = "tr ~ (uutils) translate characters within input and display"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/tr"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/tr.rs"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
uucore = { version=">=0.0.9", package="uucore", path="../../uucore" }
uucore_procs = { version=">=0.0.6", package="uucore_procs", path="../../uucore_procs" }
nom = "5.1.2"

[[bin]]
name = "tr"
path = "src/main.rs"

[package.metadata.cargo-udeps.ignore]
# Necessary for "make all"
normal = ["uucore_procs"]
