[book]
authors = ["uutils contributors"]
language = "en"
multilingual = false
src = "src"
title = "Uutils Documentation"

[output.html]
git-repository-url = "https://github.com/rust-lang/cargo/tree/master/src/doc/src"